version: "2"
services:
  postfix:
     image: rahonabe/postfix
     hostname: <yourhostnamehere>
     domainname: <yourdomainhere>
     environment:
      - MYORIGIN=<youroriginhere>
      - MYNETWORKS=<ipofyournetworkcontainer>
     build: 
      context: .
networks:
  default:
    external:
      name: yournetworkcontainers
